In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('sonardataset.csv')
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [3]:
df.shape

(208, 61)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  y       208 non-null    str
dtypes: float64(60), str(1)
memory usage: 99.5 KB

In [5]:
df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [6]:
df.isnull().sum()

x_1     0
x_2     0
x_3     0
x_4     0
x_5     0
       ..
x_57    0
x_58    0
x_59    0
x_60    0
y       0
Length: 61, dtype: int64

In [7]:
data = df.drop_duplicates()
data.duplicated().sum()

np.int64(0)

In [8]:
x = data.drop(columns=[data.columns[-1]])
y = data[data.columns[-1]]

In [9]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_scaled = scaler.fit_transform(x)

In [10]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
y_en = encoder.fit_transform(y.values.reshape(-1, 1))
y_encoded = pd.DataFrame(y_en.toarray())

NotImplementedError: <class 'pandas.arrays.ArrowStringArray'> does not support reshape as backed by a 1D pyarrow.ChunkedArray.

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y_encoded, test_size=0.2, random_state=42)

NameError: name 'y_encoded' is not defined

In [12]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model1 = Sequential([
    Dense(12, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(y_encoded.shape[1], activation='softmax')
])

model1.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
training = model1.fit(x_train, y_train, epochs=20, batch_size=20, validation_split=0.2)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788887613.731085   34673 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1788887613.731892   34673 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1788887613.810539   34673 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788887615.882614   34673 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1788887615.883114   34673 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

NameError: name 'x_train' is not defined

In [13]:
model2 = Sequential([
    Dense(56, activation='relu', input_shape=(x_train.shape[1],)),
    Dense(y_encoded.shape[1], activation='sigmoid')
])

model2.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model2.fit(x_train, y_train, epochs=20, batch_size=42, validation_split=0.2)

NameError: name 'x_train' is not defined

In [14]:
model3 = Sequential([
    Dense(56, activation='elu', input_shape=(x_train.shape[1],)),
    Dense(y_encoded.shape[1], activation='sigmoid')
])

model3.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model3.fit(x_train, y_train, epochs=20, batch_size=42, validation_split=0.2)

NameError: name 'x_train' is not defined

In [15]:
model3 = Sequential([
    Dense(56, activation='elu', input_shape=(x_train.shape[1],)),
    Dense(y_encoded.shape[1], activation='sigmoid')
])

model3.compile(optimizer='RMSprop', loss='categorical_crossentropy', metrics=['accuracy'])
training = model3.fit(x_train, y_train, epochs=20, batch_size=42, validation_split=0.2)

NameError: name 'x_train' is not defined

In [16]:
model4 = Sequential([
    Dense(56, activation='tanh', input_shape=(x_train.shape[1],)),
    Dense(y_encoded.shape[1], activation='sigmoid')
])

model4.compile(optimizer='Adagrad', loss='categorical_crossentropy', metrics=['accuracy'])
training = model4.fit(x_train, y_train, epochs=20, batch_size=42, validation_split=0.2)

NameError: name 'x_train' is not defined

In [17]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
import numpy as np

y_true = np.argmax(y_test.values, axis=1)
y_pred = np.argmax(model1.predict(x_test), axis=1)

print("Model 1 relu softmax adam")
print(accuracy_score(y_true, y_pred),
      precision_score(y_true, y_pred, average='weighted'),
      recall_score(y_true, y_pred, average='weighted'),
      f1_score(y_true, y_pred, average='weighted'))

NameError: name 'y_test' is not defined

In [18]:
y_pred = np.argmax(model2.predict(x_test), axis=1)

print("Model 2 relu sigmoid RMSprop")
print(accuracy_score(y_true, y_pred),
      precision_score(y_true, y_pred, average='weighted'),
      recall_score(y_true, y_pred, average='weighted'),
      f1_score(y_true, y_pred, average='weighted'))

NameError: name 'model2' is not defined

In [19]:
y_pred = np.argmax(model3.predict(x_test), axis=1)

print("Model 3 elu sigmoid RMSprop")
print(accuracy_score(y_true, y_pred),
      precision_score(y_true, y_pred, average='weighted'),
      recall_score(y_true, y_pred, average='weighted'),
      f1_score(y_true, y_pred, average='weighted'))

NameError: name 'model3' is not defined

In [20]:
y_pred = np.argmax(model4.predict(x_test), axis=1)

print("Model 4 tanh Adagrad")
print(accuracy_score(y_true, y_pred),
      precision_score(y_true, y_pred, average='weighted'),
      recall_score(y_true, y_pred, average='weighted'),
      f1_score(y_true, y_pred, average='weighted'))

NameError: name 'model4' is not defined